// ============================================================================
// Phone OTP Login Service (Message Central VerifyNow + Shopify classic accounts)
//
// Provider: Message Central VerifyNow (cpaas.messagecentral.com). Their OTP
// route delivers in India WITHOUT DLT registration. (MSG91 and 2factor.in
// were both dropped: their local SMS routes require paid DLT registration
// before any SMS delivers in India.)
//
// API contract (v3, per the official VerifyNow onboarding guide):
//   send:   POST /verification/v3/send?countryCode=91&customerId&flowType=SMS&type=OTP&mobileNumber&otpLength
//   verify: POST /verification/v3/validateOtp?verificationId&code&flowType=SMS&customerId
//   Auth: the authToken is issued by the Message Central console
//   (Developer Guide > API Credentials) and used verbatim via MC_AUTH_TOKEN.
//   Optional fallback: MC_PASSWORD + MC_ACCOUNT_EMAIL fetch a token via
//   POST /auth/v1/authentication/token.
//
// Flow:
//   1. /api/auth/otp/send   -> VerifyNow sends the OTP
//                              (dev mode: logs to console when unconfigured)
//   2. /api/auth/otp/verify -> VerifyNow validateOtp checks the OTP, then:
//        a. Find Shopify customer by phone (Admin API) - create if missing
//        b. Generate a one-time account activation URL via Admin API
//           (customerGenerateAccountActivationUrl equivalent - NO email needed,
//           unlike the password-reset-token trick which requires intercepting
//           the reset email Shopify sends)
//        c. Activate the account server-side by POSTing the storefront
//           activation form with a random password
//        d. Return { action, email, password } so the storefront JS submits a
//           normal /account/login form (same-origin -> Shopify issues the
//           _secure_customer_session cookie directly in the browser)
//
// Limitation: customers whose legacy account is ALREADY activated
// (state === 'enabled') keep their own password and must use email login.
//
// Env vars:
//   SHOPIFY_STORE, SHOPIFY_ACCESS_TOKEN      (already present)
//   MC_CUSTOMER_ID                           (Message Central console)
//   MC_AUTH_TOKEN                            (console > Developer Guide >
//                                             API Credentials > Auth Token)
//   MC_PASSWORD / MC_ACCOUNT_EMAIL           (optional fallback: fetch a token
//                                             at runtime instead of using the
//                                             static one from the console)
//   MC_BASE_URL                              (optional override)
//   OTP_CUSTOMER_EMAIL_DOMAIN                (optional; domain for synthetic
//                                             emails of new phone-only accounts,
//                                             defaults to SHOPIFY_STORE)
// ============================================================================

const crypto = require('crypto');

const SHOPIFY_API_VERSION = '2024-01';
const STOREFRONT_USER_AGENT = 'Mozilla/5.0 (compatible; OFFCOMFRT-OTP/1.0)';

const OTP_LENGTH = 6;                        // digits, generated by VerifyNow
const OTP_TTL_MS = 5 * 60 * 1000;            // OTP valid for 5 minutes
const OTP_RESEND_COOLDOWN_MS = 60 * 1000;    // 1 minute between sends
const OTP_MAX_SENDS_PER_HOUR = 3;            // per phone number
const OTP_MAX_VERIFY_ATTEMPTS = 5;           // before the OTP is invalidated

// In-memory OTP session store: phone -> session record.
// OTPs are short-lived so in-memory storage is fine for a single Render instance.
const otpStore = new Map();

// Prune expired entries so the Map doesn't grow unbounded
setInterval(() => {
    const now = Date.now();
    for (const [phone, record] of otpStore) {
        // Drop records whose OTP expired AND whose send history fully aged out
        const recentSends = record.sendTimes.filter(ts => now - ts < 60 * 60 * 1000);
        if (record.expiresAt < now && recentSends.length === 0) {
            otpStore.delete(phone);
        } else {
            record.sendTimes = recentSends;
        }
    }
}, 10 * 60 * 1000).unref();

// Structured error so routes can map codes -> HTTP statuses
class OtpError extends Error {
    constructor(code, message, status = 400) {
        super(message);
        this.code = code;
        this.status = status;
    }
}

// ------------------------------ helpers -------------------------------------

function sha256(value) {
    return crypto.createHash('sha256').update(String(value)).digest('hex');
}

/**
 * Normalize user input to a 12-digit Indian number with country code
 * (e.g. "98765 43210", "09876543210", "+91 9876543210" -> "919876543210").
 * Returns null when the input is not a valid Indian mobile.
 */
function normalizeIndianPhone(input) {
    if (!input) return null;
    const cleaned = String(input).replace(/[^\d]/g, '');
    let digits = null;
    if (cleaned.length === 10) {
        digits = '91' + cleaned;
    } else if (cleaned.length === 11 && cleaned.startsWith('0')) {
        digits = '91' + cleaned.substring(1);
    } else if (cleaned.length === 12 && cleaned.startsWith('91')) {
        digits = cleaned;
    }
    if (!digits) return null;
    // Indian mobiles start with 6-9 after the country code
    if (!/^[6-9]/.test(digits.substring(2))) return null;
    return digits;
}

function isVerifyNowConfigured() {
    return !!(process.env.MC_CUSTOMER_ID &&
        (process.env.MC_AUTH_TOKEN || (process.env.MC_PASSWORD && process.env.MC_ACCOUNT_EMAIL)));
}

function mcBase() {
    return process.env.MC_BASE_URL || 'https://cpaas.messagecentral.com';
}

// ------------------------------ Message Central ------------------------------

// VerifyNow auth tokens are JWTs valid for days; cache and refresh on expiry
// so every OTP send doesn't burn an extra token call.
let cachedToken = { value: null, expiresAt: 0 };

async function getAuthToken(forceRefresh = false) {
    // Preferred: the long-lived token issued by the console (API Credentials
    // page). No password exchange needed.
    if (process.env.MC_AUTH_TOKEN) {
        return process.env.MC_AUTH_TOKEN;
    }

    const now = Date.now();
    if (!forceRefresh && cachedToken.value && cachedToken.expiresAt > now) {
        return cachedToken.value;
    }

    const params = new URLSearchParams({
        customerId: process.env.MC_CUSTOMER_ID,
        key: Buffer.from(process.env.MC_PASSWORD).toString('base64'),
        scope: 'NEW',
        country: '91',
        email: process.env.MC_ACCOUNT_EMAIL
    });

    let response;
    try {
        response = await fetch(`${mcBase()}/auth/v1/authentication/token?${params.toString()}`, {
            method: 'POST',
            signal: AbortSignal.timeout(15000)
        });
    } catch (err) {
        console.error('[OTP] VerifyNow token request failed:', err.message);
        throw new OtpError('provider_error', 'Could not send OTP right now. Please try again.', 502);
    }

    let data = null;
    try { data = await response.json(); } catch { /* non-JSON response */ }
    const token = data?.data?.authToken || data?.authToken || null;

    if (response.status !== 200 || !token) {
        console.error('[OTP] VerifyNow token rejected:', response.status, JSON.stringify(data));
        throw new OtpError('provider_error', 'Could not send OTP right now. Please try again.', 502);
    }

    // Tokens last days server-side; refresh daily to stay safely inside
    cachedToken = { value: token, expiresAt: now + 20 * 60 * 60 * 1000 };
    return token;
}

async function sendOtp(phone) {
    const now = Date.now();
    const existing = otpStore.get(phone);

    if (existing) {
        if (existing.cooldownUntil > now) {
            const retryInSeconds = Math.ceil((existing.cooldownUntil - now) / 1000);
            throw new OtpError('resend_too_soon', `Please wait ${retryInSeconds}s before requesting another OTP`, 429);
        }
        const sendsLastHour = existing.sendTimes.filter(ts => now - ts < 60 * 60 * 1000);
        if (sendsLastHour.length >= OTP_MAX_SENDS_PER_HOUR) {
            throw new OtpError('send_limit', 'Too many OTP requests for this number. Try again after an hour.', 429);
        }
    }

    let sessionId = null;
    let devOtp = null;

    const configured = isVerifyNowConfigured();
    console.log(`[OTP] send request for +${phone} | VerifyNow configured: ${configured}`);

    if (configured) {
        // VerifyNow generates the OTP itself and returns a verificationId
        // that validateOtp needs later. mobileNumber is sent WITHOUT the
        // country code (countryCode is a separate param).
        const params = new URLSearchParams({
            countryCode: '91',
            customerId: process.env.MC_CUSTOMER_ID,
            flowType: 'SMS',
            type: 'OTP',
            mobileNumber: phone.substring(2),
            otpLength: String(OTP_LENGTH)
        });
        const url = `${mcBase()}/verification/v3/send?${params.toString()}`;

        let response;
        try {
            response = await fetch(url, {
                method: 'POST',
                headers: { authToken: await getAuthToken() },
                signal: AbortSignal.timeout(15000)
            });
        } catch (err) {
            console.error('[OTP] VerifyNow send request failed:', err.message);
            throw new OtpError('provider_error', 'Could not send OTP right now. Please try again.', 502);
        }

        let data = null;
        try { data = await response.json(); } catch { /* non-JSON response */ }

        // Token expired mid-flight (password-mode only - a static console
        // token can't be refreshed): fetch a fresh one and retry the send
        if ((response.status === 401 || response.status === 403) && !process.env.MC_AUTH_TOKEN) {
            try {
                response = await fetch(url, {
                    method: 'POST',
                    headers: { authToken: await getAuthToken(true) },
                    signal: AbortSignal.timeout(15000)
                });
                try { data = await response.json(); } catch { /* non-JSON */ }
            } catch (err) {
                console.error('[OTP] VerifyNow send retry failed:', err.message);
                throw new OtpError('provider_error', 'Could not send OTP right now. Please try again.', 502);
            }
        }

        const ok = response.status === 200 && !!data && data.message === 'SUCCESS' && data.data?.verificationId;
        if (!ok) {
            console.error('[OTP] VerifyNow send failed:', response.status, JSON.stringify(data));
            throw new OtpError('provider_error', 'Could not send OTP right now. Please try again.', 502);
        }
        sessionId = data.data.verificationId;
        console.log(`[OTP] VerifyNow accepted send for +${phone} | verificationId: ${sessionId}`);
    } else {
        // Dev mode: no VerifyNow credentials - generate the OTP locally and log it.
        devOtp = String(Math.floor(100000 + Math.random() * 900000));
        console.log(`[OTP][DEV] OTP for +${phone}: ${devOtp}`);
    }

    const record = existing || { sendTimes: [], attempts: 0 };
    record.sessionId = sessionId;
    record.otpHash = devOtp ? sha256(devOtp) : null;
    record.expiresAt = now + OTP_TTL_MS;
    record.cooldownUntil = now + OTP_RESEND_COOLDOWN_MS;
    record.attempts = 0;
    record.sendTimes = [...(record.sendTimes || []), now];
    otpStore.set(phone, record);

    return {
        via: configured ? 'verifynow' : 'dev',
        expiresInSeconds: Math.round(OTP_TTL_MS / 1000),
        resendInSeconds: Math.round(OTP_RESEND_COOLDOWN_MS / 1000),
        devOtp: devOtp && process.env.NODE_ENV !== 'production' ? devOtp : undefined
    };
}

async function verifyOtp(phone, otp) {
    const now = Date.now();
    const record = otpStore.get(phone);

    if (!record || record.expiresAt < now) {
        throw new OtpError('otp_expired', 'OTP expired. Please request a new one.', 410);
    }
    if (record.attempts >= OTP_MAX_VERIFY_ATTEMPTS) {
        otpStore.delete(phone);
        throw new OtpError('otp_locked', 'Too many incorrect attempts. Please request a new OTP.', 429);
    }
    record.attempts += 1;

    let ok = false;

    if (isVerifyNowConfigured()) {
        if (!record.sessionId) {
            throw new OtpError('otp_expired', 'OTP expired. Please request a new one.', 410);
        }

        // validateOtp (v3): verificationId from the send call + the user's code
        const params = new URLSearchParams({
            verificationId: record.sessionId,
            code: String(otp),
            flowType: 'SMS',
            customerId: process.env.MC_CUSTOMER_ID
        });
        const url = `${mcBase()}/verification/v3/validateOtp?${params.toString()}`;

        let response;
        try {
            response = await fetch(url, {
                method: 'POST',
                headers: { authToken: await getAuthToken() },
                signal: AbortSignal.timeout(15000)
            });
        } catch (err) {
            console.error('[OTP] VerifyNow verify request failed:', err.message);
            throw new OtpError('provider_error', 'Could not verify OTP right now. Please try again.', 502);
        }

        let data = null;
        try { data = await response.json(); } catch { /* non-JSON response */ }
        ok = response.status === 200 && !!data &&
            data.data?.verificationStatus === 'VERIFICATION_COMPLETED';

        console.log(`[OTP] VerifyNow verify response for +${phone} | status: ${response.status} | body: ${JSON.stringify(data)}`);

        if (!ok) {
            console.warn(`[OTP] Verify rejected for +${phone} (attempt ${record.attempts}/${OTP_MAX_VERIFY_ATTEMPTS})`);
        }
    } else {
        // Dev mode: compare against the locally generated OTP
        ok = record.otpHash === sha256(String(otp));
    }

    if (!ok) {
        const remaining = OTP_MAX_VERIFY_ATTEMPTS - record.attempts;
        throw new OtpError('otp_invalid', remaining > 0
            ? `Incorrect OTP. ${remaining} attempt(s) remaining.`
            : 'Incorrect OTP. Please request a new one.', 401);
    }

    otpStore.delete(phone); // single-use
    return true;
}

// ------------------------------ Shopify -------------------------------------

async function shopifyAdmin(endpoint, options = {}) {
    const token = process.env.SHOPIFY_ACCESS_TOKEN;
    const shop = process.env.SHOPIFY_STORE;
    if (!token || !shop) {
        throw new OtpError('not_configured', 'Shopify credentials are not configured', 500);
    }

    const url = endpoint.startsWith('http')
        ? endpoint
        : `https://${shop}/admin/api/${SHOPIFY_API_VERSION}/${endpoint}`;

    const response = await fetch(url, {
        ...options,
        headers: {
            'X-Shopify-Access-Token': token,
            'Content-Type': 'application/json',
            ...options.headers
        },
        signal: AbortSignal.timeout(20000)
    });

    if (!response.ok) {
        const errorText = await response.text();
        throw new OtpError('shopify_error', `Shopify API error: ${response.status} - ${errorText}`, 502);
    }

    return response.status === 204 ? {} : response.json();
}

async function findCustomerByPhone(phone) {
    const e164 = `+${phone}`;
    // Try E.164 first, then the bare digits (stores store phone formats inconsistently)
    for (const query of [e164, phone]) {
        const data = await shopifyAdmin(`customers.json?phone=${encodeURIComponent(query)}&limit=1`);
        const customer = data.customers?.[0];
        if (customer) return customer;
    }
    return null;
}

function syntheticEmail(phone) {
    const domain = process.env.OTP_CUSTOMER_EMAIL_DOMAIN || process.env.SHOPIFY_STORE;
    return `${phone}@${domain}`;
}

async function createCustomer(phone) {
    const payload = {
        customer: {
            email: syntheticEmail(phone),
            phone: `+${phone}`,
            first_name: 'Customer',
            tags: 'otp-login',
            send_email_invite: false
        }
    };

    try {
        const data = await shopifyAdmin('customers.json', {
            method: 'POST',
            body: JSON.stringify(payload)
        });
        return data.customer;
    } catch (err) {
        // Email collision (shouldn't happen, but recover gracefully)
        if (err.message.includes('422')) {
            const byEmail = await shopifyAdmin(`customers.json?email=${encodeURIComponent(syntheticEmail(phone))}&limit=1`);
            if (byEmail.customers?.[0]) return byEmail.customers[0];
        }
        throw err;
    }
}

async function generateActivationUrl(customerId) {
    const data = await shopifyAdmin(`customers/${customerId}/account_activation_url.json`, {
        method: 'POST'
    });
    const activationUrl = data.account_activation_url?.activation_url;
    if (!activationUrl) {
        throw new OtpError('activation_url_failed', 'Could not generate an account activation link', 502);
    }
    return activationUrl;
}

// Extract hidden form inputs from a Shopify storefront page
function parseHiddenInputs(html) {
    const hidden = {};
    const matches = html.match(/<input[^>]*type=["']hidden["'][^>]*>/gi) || [];
    for (const tag of matches) {
        const nameMatch = tag.match(/name=["']([^"']+)["']/i);
        const valueMatch = tag.match(/value=["']([^"']*)["']/i);
        if (nameMatch) hidden[nameMatch[1]] = valueMatch ? valueMatch[1] : '';
    }
    return hidden;
}

function randomPassword() {
    return crypto.randomBytes(18).toString('base64url');
}

/**
 * Activate (or re-set the password of) an account using the one-time
 * activation URL. GETs the activation page, copies its hidden form fields,
 * then POSTs the new password back to the same URL.
 */
async function activateAccount(activationUrl, password) {
    let page;
    try {
        page = await fetch(activationUrl, {
            headers: { 'User-Agent': STOREFRONT_USER_AGENT },
            redirect: 'manual',
            signal: AbortSignal.timeout(20000)
        });
    } catch (err) {
        throw new OtpError('storefront_error', 'Could not reach the store to activate the account', 502);
    }

    // A redirect here means the link was already consumed/expired
    if (page.status !== 200) {
        throw new OtpError('activation_link_invalid', 'Activation link expired. Please try logging in again.', 502);
    }

    const html = await page.text();
    const hidden = parseHiddenInputs(html);
    if (!hidden.form_type) {
        throw new OtpError('activation_link_invalid', 'Unexpected activation page format', 502);
    }

    const form = new URLSearchParams();
    for (const [name, value] of Object.entries(hidden)) form.append(name, value);
    form.append('customer[password]', password);
    form.append('customer[password_confirmation]', password);

    let result;
    try {
        result = await fetch(activationUrl, {
            method: 'POST',
            headers: {
                'User-Agent': STOREFRONT_USER_AGENT,
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: form.toString(),
            redirect: 'manual',
            signal: AbortSignal.timeout(20000)
        });
    } catch (err) {
        throw new OtpError('storefront_error', 'Could not reach the store to activate the account', 502);
    }

    // Success: Shopify 302s to the account page. A 200 re-renders the form with errors.
    if (result.status >= 300 && result.status < 400) return true;

    const body = await result.text().catch(() => '');
    const errorMatch = body.match(/errors">\s*<li[^>]*>([^<]+)</i) || body.match(/class="error[^"]*"[^>]*>([^<]+)</i);
    throw new OtpError('activation_failed',
        errorMatch ? `Account activation failed: ${errorMatch[1].trim()}` : 'Account activation failed', 502);
}

/**
 * Full verify-otp backend flow: find/create customer, activate account,
 * return the storefront login credentials for the theme to submit.
 */
async function issueStorefrontLogin(phone) {
    const shop = process.env.SHOPIFY_STORE;
    if (!shop) throw new OtpError('not_configured', 'SHOPIFY_STORE is not configured', 500);

    let customer = await findCustomerByPhone(phone);
    if (!customer) {
        customer = await createCustomer(phone);
        console.log(`[OTP] Created Shopify customer ${customer.id} for +${phone}`);
    }

    // Already-activated accounts have a password we cannot override -
    // those users must log in with email + password.
    if (customer.state === 'enabled') {
        throw new OtpError('already_active',
            'This account already has a password. Please use email + password login.', 409);
    }

    if (!customer.email) {
        throw new OtpError('no_email', 'This account has no email on file. Please contact support.', 409);
    }

    const password = randomPassword();
    const activationUrl = await generateActivationUrl(customer.id);
    await activateAccount(activationUrl, password);

    return {
        action: `https://${shop}/account/login`,
        email: customer.email,
        password,
        redirect: '/account'
    };
}

module.exports = {
    normalizeIndianPhone,
    sendOtp,
    verifyOtp,
    issueStorefrontLogin,
    OtpError
};
